name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: 构建PDF
    runs-on: ubuntu-latest
    env:
      OUTPUT: FromCToPython.pdf

    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3

      - run: typst compile main.typ $OUTPUT --font-path fonts

      - uses: actions/upload-artifact@v4
        with:
          path: $OUTPUT
