name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: 构建PDF
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
      - uses: fontist/setup-fontist@v2

      - run: fontist install "Noto Serif CJK"
      - run: typst compile main.typ main.pdf --font-path ~/.fontist/fonts:font

      - uses: actions/upload-artifact@v4
        with:
          name: FromCToPython.pdf
          path: main.pdf
